[package]
name = "sappho-identmap"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies.sappho-unparse]
path = "../unparse"

[dependencies.sappho-listform]
path = "../listform"
