[package]
name = "sappho-identmap"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
sappho-listform.workspace = true
sappho-unparse.workspace = true
