[package]
name = "sappho-value"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99.17"

[dependencies.sappho-east]
path = "../east"

[dependencies.sappho-fmtutil]
path = "../fmtutil"

[dependencies.sappho-identmap]
path = "../identmap"

[dependencies.sappho-object]
path = "../object"
