[workspace]
members = [
  "ast",
  "cli",
  "ast-reduced",
  "eval",
  "unparse",
  "astcore",
  "identmap",
  "integration-tests",
  "interpreter",
  "listform",
  "object",
  "parser",
  "source",
  "transform",
  "value",
]
