[workspace]
members = [
  "ast",
  "ast-core",
  "ast-reduced",
  "cli",
  "eval",
  "identmap",
  "integration-tests",
  "interpreter",
  "listform",
  "object",
  "parser",
  "source",
  "transform",
  "unparse",
  "value",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "gplv3"
homepage = "https://github.com/nathan-at-least/sappho"
