[workspace]
members = [
  "ast",
  "cli",
  "east",
  "eval",
  "fmtutil",
  "gast",
  "identmap",
  "integration-tests",
  "interpreter",
  "object",
  "parser",
  "source",
  "transform",
  "value",
]
