[package]
name = "sappho-object"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
derive_more.workspace = true
sappho-identmap.workspace = true
sappho-unparse.workspace = true
