[package]
name = "sappho-object"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
derive-new = "0.5.9"

sappho-identmap.workspace = true
sappho-unparse.workspace = true
