[package]
name = "saplang-eval"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99"

[dependencies.saplang-ast]
path = "../ast"

[dependencies.saplang-east]
path = "../east"

[dependencies.saplang-parser]
path = "../parser"

[dev-dependencies]
test-case = "2.0"
