[package]
name = "sappho-eval"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99"
log = "0.4.17"

[dependencies.sappho-ast]
path = "../ast"

[dependencies.sappho-east]
path = "../east"

[dependencies.sappho-gast]
path = "../gast"

[dependencies.sappho-unparse]
path = "../unparse"

[dependencies.sappho-listform]
path = "../listform"

[dependencies.sappho-value]
path = "../value"

[dev-dependencies.sappho-parser]
path = "../parser"
