[package]
name = "sappho-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
derive_more = "0.99.17"
log = "0.4.17"
simplelog = "0.12.0"

[dependencies.clap]
version = "3.1.18"
features = [
  "derive",
  "cargo",
]

[dependencies.sappho-interpreter]
path = "../interpreter"

[dependencies.sappho-parser]
path = "../parser"

[dependencies.sappho-source]
path = "../source"

[dependencies.sappho-transform]
path = "../transform"
