[package]
name = "sappho-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99.17"

[dependencies.clap]
version = "3.1.18"
features = [
  "derive",
  "cargo",
]

[dependencies.sappho-east]
path = "../east"

[dependencies.sappho-interpreter]
path = "../interpreter"

[dependencies.sappho-parser]
path = "../parser"

[dependencies.sappho-source]
path = "../source"
