[package]
name = "sappho-parser"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
chumsky = "0.8"
derive_more = "0.99"

[dependencies.sappho-ast]
path = "../ast"

[dependencies.sappho-ast-core]
path = "../ast-core"

[dependencies.sappho-identmap]
path = "../identmap"

[dependencies.sappho-listform]
path = "../listform"

[dependencies.sappho-object]
path = "../object"

[dependencies.sappho-source]
path = "../source"

[dev-dependencies]
test-case = "2.0"
include_dir = "0.7"
