[package]
name = "saplang-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chumsky = "0.8"
derive_more = "0.99"

[dependencies.saplang-ast]
path = "../ast"

[dev-dependencies]
test-case = "2.0"
include_dir = "0.7"
regex = "1.5.6"
