[package]
name = "sappho-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chumsky = "0.8"
derive_more = "0.99"

[dependencies.sappho-ast]
path = "../ast"

[dependencies.sappho-gast]
path = "../gast"

[dependencies.sappho-identmap]
path = "../identmap"

[dependencies.sappho-source]
path = "../source"

[dev-dependencies]
test-case = "2.0"
include_dir = "0.7"
