[package]
name = "sappho-listform"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.sappho-fmtutil]
path = "../fmtutil"

[dev-dependencies]
test-case = "2.0"
indoc = "1.0.6"
