[package]
name = "sappho-interpreter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99.17"
pathutil = "0.1.3"

[dependencies.sappho-eval]
path = "../eval"

[dependencies.sappho-parser]
path = "../parser"

[dependencies.sappho-source]
path = "../source"
