[package]
name = "sappho-transform"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
sappho-ast-reduced.workspace = true
sappho-ast.workspace = true
