[package]
name = "sappho-transform"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies.sappho-ast]
path = "../ast"

[dependencies.sappho-ast-reduced]
path = "../ast-reduced"
