[package]
name = "sappho-integration-tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
indoc = "1.0.6"
pathutil = "0.1.2"

[dev-dependencies]
derive_more = "0.99.17"

[dev-dependencies.sappho-east]
path = "../east"

[dev-dependencies.sappho-interpreter]
path = "../interpreter"

[dev-dependencies.sappho-parser]
path = "../parser"
