[package]
name = "sappho-source"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
anyhow.workspace = true
anyhow-std.workspace = true
